- hosts: webservers
  gather_facts: no

  tasks:
    - name: Git pull
      git:
        repo: https://github.com/zipofar/redsoft-test.git 
        dest: /home/ingprog/apps/redsoft-test
        update: yes
        version: master

    - name: Run makefile ansible-production-setup
      make:
        chdir: /home/ingprog/apps/redsoft-test
        target: ansible-production-setup

    - name: Run makefile production-setup
      make:
        chdir: /home/ingprog/apps/redsoft-test
        target: production-setup