- hosts: webservers
  gather_facts: no

  tasks:
    - name: Git pull
      git:
        repo: https://github.com/zipofar/redsoft-test.git 
        dest: /home/ingprog/apps/redsoft-test
        update: yes
        version: master

    - name: Run makefile production-setup
      make:
        chdir: /home/ingprog/apps/redsoft-test
        target: production-setup

    - name: Make env for Docker
      template:
        src: templates/env_docker.j2
        dest: '../.env'

    - name: Make env for App
      template:
        src: templates/env_app.j2
        dest: '../app/.env'